### ISSUE TITLE
Add a warning message when vscode-quarkus is activated, but missing prerequisites

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#100]
For vscode-quarkus to work properly, the following is required:

* Java JDK (or JRE) 8 or more recent
* Language Support for Java(TM) by Red Hat
* Debugger for Java

What happens now:
When the requirements are not fulfilled, on extension activation, there is no error message. 

What should happen:
When the requirements are not fulfilled, there should be a warning/error message.

**Comment by fbricon** [comment]
Here's what I got when starting vscode-quarkus without vscode-java
<img width="456" alt="Screen Shot 2019-11-20 at 9 49 34 AM" src="https://user-images.githubusercontent.com/148698/69223204-38cc0880-0b7b-11ea-8c61-7252d3991627.png">

after installing the required Java extension:
<img width="455" alt="Screen Shot 2019-11-20 at 9 51 21 AM" src="https://user-images.githubusercontent.com/148698/69223296-631dc600-0b7b-11ea-9438-b4785fcb3586.png">

**Comment by xorye** [comment]
I see, this issue can be closed then. Just wondering, how did you manage to start vscode-quarkus without vscode-java and the java debugger? On my machine, the dependencies are always installed even if I install vscode-quarkus from a vsix.

Did you vscode-java and the debugger by removing them from ~/.vscode/extensions ?

**Comment by fbricon** [comment]
I deleted VS Code and reinstalled from scratch :-)
