### ISSUE TITLE
quarkus version of the generated project

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-quarkus#12]
The project that is generated with 'Generate a Maven Project"  seems to be using 'quarkus.version' 0.16. Can we change it alway use the latest and greatest?

**Comment by fbricon** [comment]
need to update the API endpoint with the latest quarkus release

**Comment by fbricon** [comment]
Basically https://github.com/xorye/quarkus-generator is built as a docker image, pushed to quay.io and eventually deployed to http://quarkus-generator.6923.rh-us-east-1.openshiftapps.com

**Comment by gorkem** [comment]
Isn't there an endpoint that is kept up-to-date already?

**Comment by fbricon** [comment]
Not that I know of. https://github.com/quarkusio/quarkus/issues/447 is still open. Our endpoint is a fork of the proposed endpoint

**Comment by fbricon** [comment]
The endpoint now generates quarkus 0.20.0 projects

**Comment by fbricon** [comment]
Fixed with the use of https://code.quarkus.io endpoint (#18)

**Comment by luszczynski** [comment]
A new project generated using the vscode extension is using quarkus `0.20.0`. The latest version is `0.23.2`. Is there any plan for getting always the latest version?
