### ISSUE TITLE
How to change default port number 5005?

### ISSUE THREAD

**Issue by jdang67** [redhat-developer/vscode-quarkus#121]
Hi,

I need to run more than one app at the same time. I can change the http port number from 8080 to any number I want but I could not find a way to change default port 5005 when starting the second app.  Any help is appreciated.

Thanks,
Jdang 

```  .js
[INFO] --- quarkus-maven-plugin:0.23.2:dev (default-cli) @ kafka.restapi ---
[ERROR] Port 5005 in use, not starting in debug mode
```

**Comment by fbricon** [comment]
You can change the debug port (to say 6006)  by either 
- setting `<debug>6006</debug>` in the quarkus-maven-plugin configuration,
- or calling the quarkus:dev goal with -Ddebug=6006.

If you use the "Debug current Quarkus project" command or launch configuration in VS Code, you'll need to do a couple changes:
- in .vscode/tasks.json, set `"command": "./mvnw quarkus:dev -Ddebug=6006"` (similar change for windows)
- in .vscode/launch.json, set `"port": 6006`

See:
<img width="1171" alt="Screen Shot 2019-10-22 at 7 02 22 PM" src="https://user-images.githubusercontent.com/148698/67310678-86167500-f4fe-11e9-8b22-832fee44cde7.png">

**Comment by jdang67** [comment]
Hi Fbricon, 

Thanks for your help. I used this technique weeks ago after goes over the documentation. However,  it does not do anything, there is no log output. What I'm missing here?

thanks,
Jdang

``` java
[INFO] --- quarkus-maven-plugin:0.23.2:dev (default-cli) @  myApp---
[WARNING] The POM for io.sundr:sundr-codegen:jar:0.19.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
Listening for transport dt_socket at address: 5007

**Comment by fbricon** [comment]
please attach a sample project reproducing the issue

**Comment by jdang67** [comment]
The problem was the collision of Http port 8080 but the app does not show the exception in the console. Changing the default port 8080 to something else works.
