### ISSUE TITLE
generate launch.json

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-quarkus#13]
Generate a 'launch.json' with at least one configuration to attach a debugger to quarkus started on dev mode.

**Comment by fbricon** [comment]
So apparently we need to generate 2 things:
- a new task in .vscode/tasks.json
```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
        "label": "quarkus:dev",
        "type": "shell",
        "command": "./mvnw quarkus:dev",
        "windows": {
            "command": ".\\mvn.cmd quarkus:dev"
        },
        "isBackground": true,
        "problemMatcher": [{
            "pattern": [{
                "regexp": "\\b\\B",
                "file": 1,
                "location": 2,
                "message": 3
            }],
            "background": {
                "activeOnStart": true,
                "beginsPattern": "^.*Scanning for projects...*",
                "endsPattern": "^.*Quarkus .* started in .*\\. Listening on:*"
            }
        }]
    }
    ]
}
```

and a new launch configuration in launch.json:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "preLaunchTask": "quarkus:dev",
            "type": "java",
            "request": "attach",
            "hostName": "localhost",
            "name": "Debug Quarkus application",
            "port": 5005
        }
    ]
}
```

With those 2 files, hitting F5 will first start the `./mvnw quarkus:dev` task, then attach to the debugger on port 5005. It works pretty well.
We could add those files automatically to the new unzipped project. @gorkem wdyt?

**Comment by fbricon** [comment]
That approach is significantly different from @tsurdilo 's command https://github.com/tsurdilo/quarkus-vsc/commit/d2a661a28d883bbf6d882e0669c37fcbfd19eba5 though. What I propose would work OOTB on new projects by hitting F5, @tsurdilo 's approach can work on any project without specific tasks.json or launch.json, but needs to open the command palette for launch or bind the command to a shortcut, and forces users to use port 8081.

**Comment by fbricon** [comment]
Another drawback of my solution is that If you click on the disconnect button, the quarkus:dev process is still running in the background. you need to explicitely stop it with ctrl+c. But, if instead you hit F5 again, the debugger reattaches itself without restarting quarkus:dev. Could be a curse or a blessing.

**Comment by xorye** [comment]
VS Code officially supports detecting when the debugger disconnects with 
 [`onDidTerminateDebugSession()`](https://github.com/microsoft/vscode/blob/c35caa44fffd475eac17e9e4d667cb087e152500/src/vs/vscode.d.ts#L9047).

Perhaps this could help us stop the quarkus:dev process when the user clicks on the disconnect button.

**Comment by fbricon** [comment]
If there's a way to programatically terminate background tasks then yes, on disconnect, we could show a popup asking if the user wants to terminate the running maven process (+don't ask again option)

**Comment by xorye** [comment]
Awesome, VS Code's API provides that functionality as well.
