### ISSUE TITLE
Add new header parameters when calling code.quarkus.io

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#130]
```
API consumers shoult add two new header params:
Client-Name: the name of the client (ex: "Code Quarkus")
Client-Contact-Email: the email to contact in case of change in the API
```

Client-Name: vscode-quarkus
Client-Contact-Email: fbricon (use redhat email)

@ia3andy should we add the version in the client name? Can we send multiple contact headers?

**Comment by ia3andy** [comment]
@fbricon 

>  should we add the version in the client name? 

No it'll be used for analytics purposes

> Can we send multiple contact headers?

Please send them comma separated in the `Client-Contact-Email`

Thanks
