### ISSUE TITLE
User is asked if Quarkus dev task should be terminated even if it has already been terminated

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#132]
To reproduce this behavior:

1. Ensure that "Terminate Process On Exit" is set to "Ask":
![image](https://user-images.githubusercontent.com/20326645/67953617-d9a35580-fbc5-11e9-907a-4cc0aaedd942.png)

2. In a Quarkus project, run the "Debug current Quarkus project' command in the command palette. The Quarkus dev command should run in the integrated terminal

3. In the integrated terminal, terminate the Quarkus dev process manually (Ctrl + c). This ends the debug session too.

4. The user is asked if Quarkus dev should be terminated even though it already terminated:
![image](https://user-images.githubusercontent.com/20326645/67953713-0a838a80-fbc6-11e9-9e94-ae3f6c7ff99b.png)

**Comment by xorye** [comment]
I've looked into this and discovered that this problem happens because the `vscode.debug.onDidTerminateDebugSession` event fires before `vscode.tasks.taskExecutions` (the array containing currently active tasks) is updated.

**Comment by xorye** [comment]
This is what is happening right now:

1. User terminates Quarkus Dev task with Ctrl + C
2. Debug session terminates
3. `vscode.debug.onDidTerminateDebugSession` fires
4. `vscode.tasks.onDidEndTaskProcess` fires
5. `vscode.tasks.onDidEndTask` fires

From vscode's perspective, the debug session is being terminated before the task is terminated.

I've tried to recreate this issue with a dummy task instead of the Quarkus Dev task. In a separate terminal, I ran the Quakrus Dev command so that the Quarkus application runs, and I used this script as the preLaunchTask:
```
echo "Scanning for projects..."
echo "Quarkus 1.0.0.CR1 started in 1.429s. Listening on: http://0.0.0.0:8080"
sleep 10000
```

When terminating the dummy task with `Ctrl+C`, the debug session didn't end automatically. I think this is expected behaviour, as vscode doesn't know whether or not the preLaunchTask runs a process that runs the actual application being debugged.

So I am unsure why terminating a Quarkus Dev task with `Ctrl+C` automatically terminates any attached debuggers.

@fbricon Could this be a Quarkus specific thing? Maybe the Quarkus Dev task intercepts the `Ctrl+C` signal and manually detaches all attached debuggers?

**Comment by xorye** [comment]
I realized this is what seems to happen:

1. Ctrl + C to terminate quarkus dev, quarkus dev process starts a shutdown thread
2. Shutdown thread terminate quarkus application jar process
3. Step 2 causes the debug session to close, because there is no application to debug anymore
4. Shutdown thread complete, quarkus:dev process terminates

Because the debug session exits before quarkus dev terminates, the simplest solution to this issue would be to introduce a set timeout if the terminate setting is set to 'Ask'. The set timeout is to make sure that the quarkus dev task has finished terminating.

**Comment by xorye** [comment]
@fbricon should we go with the `setTimeout()` solution (mentioned in my previous post) for now?

**Comment by fbricon** [comment]
If we can keep the timeout to < 1s, while improving the UX, then sure it's worth trying
