### ISSUE TITLE
Last used extensions is empty in vscode insiders

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#138]
https://github.com/xorye/vscode-quarkus/blob/1212ea057f04c13dfaad842bb0d538e8e30ee213/src/QuarkusConfig.ts#L69 returns an empty array in insiders

looks like a regression in vscode (need to open bug upstream). We've been abusing preferences to store data, but we should prolly use the global state to store last used configuration instead

**Comment by xorye** [comment]
> https://github.com/xorye/vscode-quarkus/blob/1212ea057f04c13dfaad842bb0d538e8e30ee213/src/QuarkusConfig.ts#L69 returns an empty array in insiders

@fbricon sorry, my mistake. It works. I must have not added it to the settings.json file for insiders

**Comment by xorye** [comment]
The first item (Last used extension) was not visible. I've made an issue here https://github.com/microsoft/vscode/issues/84150

**Comment by fbricon** [comment]
Fixed upstream
