### ISSUE TITLE
vscode-quarkus reports "Unknown Property" in application.properties file when using @ConfigProperties on a class/interface

### ISSUE THREAD

**Issue by nyehamene** [redhat-developer/vscode-quarkus#155]
When using a class/interface annotated with `@ConfigProperties` without annotating the fields or methods with `@ConfigProperty`, associated properties in the `application.properties` file are shown as _Unknown Properties_ in vscode. It becomes hard to tell when a property is backed by a field in a class, or when it isn't.

_For example:_
```
@ConfigProperties(prefix = "hello")
public interface HelloConfiguration {
    @ConfigProperty(name = "message")
    public String message;
    public String suffix;
    public Optional<String> name;
}
```
given the above class definition, vscode reports the following properties as unknown properties.
```
hello.message=???
hello.suffix=???
hello.name=???
```
It would be great if vscode was able to map fields in a class annotated with the `@ConfigProperties`  to properties in the `application.properties` file in cases where the fields do not have annotation or the `name` value of the `@ConfigProperty` do not contain the configuration prefix (`hello` as in the code above with the `message` field).

**Comment by angelozerr** [comment]
@harrison-nc indeed it's a annotation that Quarkus LS should support. I'm working on this issue in https://github.com/redhat-developer/quarkus-ls/issues/136

I close this issue since it's a duplicate of https://github.com/redhat-developer/quarkus-ls/issues/136

**Comment by angelozerr** [comment]
@harrison-nc for the moment you could exclude this validation for given property `hello.message, hello.suffix` by using the `quarkus.tools.validation.unknown.excluded` settings.

vscode-quarkus 1.2.0 which will be released next week provides the capability to exclude validation with pattern. So you could write `hello.*`

**Comment by angelozerr** [comment]
@harrison-nc  vscode-quarkus 1.2.0 (should be released this week) will embed my current work redhat-developer/quarkus-ls#136

Here a demo:

![ConfigPropertiesDemo](https://user-images.githubusercontent.com/1932211/69169417-9c612200-0af8-11ea-9b45-e11528040bd4.gif)

**Comment by nyehamene** [comment]
@angelozerr thanks for the reminder, I will look forward to it.

**Comment by angelozerr** [comment]
@harrison-nc vscode-quarkus 1.2.0 has been released https://developers.redhat.com/blog/2019/11/21/new-features-in-quarkus-tools-for-visual-studio-code-1-2-0/

Please test the ConfigProperties support and give us feedback, thanks!

**Comment by nyehamene** [comment]
Thanks @angelozerr.
I've tested it and it works as expected.
