### ISSUE TITLE
Create a prompt for the user to select a new destination folder if folder with the same name already exists

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#16]
When creating a project using "Quarkus: Generate a Maven Project", if the user enters an artifact id as "demo", and chooses a destination folder which already contains a folder named "demo" the project generation wizard closes and the user is presented with this error:

![image](https://user-images.githubusercontent.com/20326645/62387486-b9152200-b528-11e9-94be-5b15992ebd77.png)

At this point, the user would have to start the project generation wizard from the beginning, all over again. 

In a situation like this, rather than an error, Spring Initializr provides this prompt:  

![image](https://user-images.githubusercontent.com/20326645/62387375-6cc9e200-b528-11e9-8253-ae1cdfab4da7.png)

This prompt allows the user to go back to the project generation wizard and choose another folder.

Having something like this for vscode-quarkus would be nice.

**Comment by gorkem** [comment]
I would consider this a bug because project creation fails without giving a reason.
