### ISSUE TITLE
vscode-quarkus should not be a Java formatter

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#166]
vscode-quarkus should not be a Java formatter.

To reproduce this issue:
1. Open a Java file while vscode-quarkus is running.
2. Right click in the editor and click "Format Document With..."
3. The user is now prompted to choose a formatter:
![image](https://user-images.githubusercontent.com/20326645/69883554-ade9bd00-12a2-11ea-8b8d-62c910887faa.png)

The "Quarkus" entry should not be present in this list, since VS Code Quarkus does not format Java files.

**Comment by angelozerr** [comment]
I think this problem comes from since we have supported CodeLens and Hover in Java file with Quarkus LS. I fear that there is no solution.

**Comment by fbricon** [comment]
@jrieken @aeschli any idea on how to get the language server register the formatter for the quarkus-properties type/language and not for java? (See https://github.com/redhat-developer/vscode-quarkus/blob/master/src/extension.ts#L128)

**Comment by jrieken** [comment]
This UI shows all installed extensions, it doesn't check if or what formatter an extension provides because we don't know that statically.... Tho, we could show formatters that we have seen contribute a formatter for that language in the past first.

**Comment by angelozerr** [comment]
@fbricon perhaps it should be better to have 2 language server :

 * one for application.properties
 * one for java file.

Today Java CodeLens, Hover uses application.properties file and don't require projectInfo, so I think we could move Java features in a new language server. Having a new language server for Java, will give the format capability as none and will fix this issue.

What do you think about that?

**Comment by angelozerr** [comment]
I don't know if it could work, but by reading https://github.com/microsoft/language-server-protocol/issues/996 we could try to follow the suggestion https://github.com/microsoft/language-server-protocol/issues/996#issuecomment-633975409

In other words when regitser capability for format (textDocument/formatting and textDocument/rangeFormatting) is sent from the server at https://github.com/redhat-developer/quarkus-ls/blob/27d554f92d8d545145410fc34cf3815f86a117bd/microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/settings/capabilities/MicroProfileCapabilityManager.java#L106 we could add `documentSelector `to say that only language `microprofile-properties` and `quarkus-properties` are supported.

```json
{
	"method": "client/registerCapability",
	"params": {
		"registrations": [
			{
				"id": "79eee87c-c409-4664-8102-e03263673f6f",
				"method": "textDocument/formatting",
				"registerOptions": {
					"documentSelector": [
						{ "language": "microprofile-properties" },
						{ "language": "quarkus-properties" }
					]
				}
			}
		]
	}
}
```
