### ISSUE TITLE
Properties leak from one project to another

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#173]
- Create a quarkus project A with no extensions
- Create a 2nd project B with quarkus-vertx, add to the same workspace
- edit B/src/main/resources/application.properties: vertx properties are present as expected
- edit A/src/main/resources/application.properties: vertx properties are present, they shouldn't be!

tested against latest master branches

**Comment by angelozerr** [comment]
@fbricon  when you don't add quarkus-vertx in dependency (your project A):

```xml
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

```

, the quarkus-vertx is in your classpath. You can see that if you open with Eclipse IDE, the pom.xml from your project A and you go the `Effective POM` :

```xml
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-vertx-core</artifactId>
        <version>1.0.1.Final</version>
      </dependency>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-vertx</artifactId>
        <version>1.0.1.Final</version>
      </dependency>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-vertx-http</artifactId>
        <version>1.0.1.Final</version>
      </dependency>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-vertx-web</artifactId>
        <version>1.0.1.Final</version>
      </dependency>

```

I suggest that you try the same test but with another extension than vertx.

**Comment by xorye** [comment]
I've tried it with quarkus-vertex and was able to reproduce the issue.
I tried again with quarkus-agroal and was not able to reproduce the issue.

Is this behavior something specific to quarkus-vertx?

**Comment by fbricon** [comment]
yeah quarkus-vertex is a transitive dependency of quarkus-resteasy so it's normal. Nothing to do here.
