### ISSUE TITLE
Add support for MicroProfile Fault Tolerance

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-quarkus#174]
See https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/configuration.asciidoc

**Comment by angelozerr** [comment]
@jclingan I have a question about generation of MP properties for fault tolerance. The documentation says:

`The override just changes the value of the corresponding parameter specified in the microservice and nothing more. If no annotation matches the specified parameter, the property will be ignored. `

The ignore is for annotation or parameter? Takes a sample, if I have:

```java
package come.acme.test;
public class MyClient{

    @Retry(maxRetries = 90, maxDuration= 1000)
    public void serviceB()
```

The available properties are:

 * come.acme.test.MyClient/serviceB/Retry/maxRetries
 * come.acme.test.MyClient/serviceB/Retry/maxDuration

But is there other properties for other Retry  parameters annotation like:

 * come.acme.test.MyClient/serviceB/Retry/jitter
... etc

**Comment by angelozerr** [comment]
@jclingan I start implementing MP Fault Tolerance, here a demo:

![MPFTDemo](https://user-images.githubusercontent.com/1932211/73726411-cb6a5580-472f-11ea-9dd9-fefc7d47cfe7.gif)

As you can see I provide all parameters for Retry annotation although the declared Retry annotation in serviceA declares only 2 parameters:

![image](https://user-images.githubusercontent.com/1932211/73726671-403d8f80-4730-11ea-9394-06c1ec2587c5.png)

@jclingan is it correct?

**Comment by xorye** [comment]
Closed with https://github.com/redhat-developer/quarkus-ls/pull/209
