### ISSUE TITLE
Improve release process to include sources when publishing vsix

### ISSUE THREAD

**Issue by nickboldt** [redhat-developer/vscode-quarkus#177]
Similar to discussions in...

* https://github.com/camel-tooling/vscode-wsdl2rest/issues/142 
* https://github.com/redhat-developer/vscode-java/issues/892
* https://github.com/redhat-developer/vscode-project-initializer/issues/40
* https://github.com/camel-tooling/vscode-camelk/issues/243
* https://github.com/windup/rhamt-vscode-extension/issues/263
* https://issues.redhat.com/browse/FUSETOOLS2-80

... we'd like that each release of this .vsix file to dl.jb.o be accompanied by a matching sources.tar.gz

I don't care if you push the .vsix to GH releases page, or tar up sources and push that to dl.jb.o, just that we have binary and sources in the same place.

Thanks!

This is a RH product security requirement in that we need to either build everything used in CodeReady Workspaces from scratch as part of our build, or else provide matching sources for upstream RH-built binaries.

**Comment by fbricon** [comment]
@nickboldt this should have been fixed with #177. Is this ok for you: https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/?C=M;O=D?

**Comment by nickboldt** [comment]
yes, but I need a /stable/ release, not a /snapshots/ one. 

https://download.jboss.org/jbosstools/vscode/stable/vscode-quarkus/

@davidkwon tells me you're planning a 1.3.0 release next week?

**Comment by fbricon** [comment]
Yes, but there's a good chance it will slip to the week after, as we found some annoying issue that need to be fixed 1st

**Comment by nickboldt** [comment]
OK np. Before mid Feb is fine for me :)

**Comment by nickboldt** [comment]
Ping! checking for new 1.3.0 in https://download.jboss.org/jbosstools/vscode/stable/vscode-quarkus/  but nothing yet. ETA still mid-early Feb?

**Comment by nickboldt** [comment]
https://download.jboss.org/jbosstools/vscode/stable/vscode-quarkus/
  | vscode-quarkus-1.3.0-242.tgz | 06-Feb-2020 13:01 | 504K |  
  | vscode-quarkus-1.3.0-242.vsix | 06-Feb-2020 13:01 | 4.7M |  

Done!
