### ISSUE TITLE
Add Qute TextMate grammar and language configuration for HTML files

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-quarkus#182]
Create a `qute.tmLanguage` which includes html TextMate like https://github.com/angelozerr/lsp4e-freemarker/blob/master/org.eclipse.lsp4e.freemarker/syntaxes/ftl.tmLanguage
You can see a demo in this repository with HTML completion (coming from the HTML Language Server of vscode and Freemarker Language Server for validation).

Perhaps a good idea is to use those file extension:

*.html.qute (or if it doesn't work .htmlQute)
*.json.qute (or if it doesn't work .jsonQute)

This language configuration could be used in Eclipse IDE too with TM4E  /cc @jeffmaury  (and I think IJ supports too TextMate)

**Comment by fbricon** [comment]
Right now, only Qute HTML is supported. Files suffixed with .qute.html will automatically be applied the Qute HTML language. The big caveat is the HTML tooling will then be disabled. If one needs to go back to getting HTML completion, hover, emmet support and so on, one needs to toggle the language mode on the right side of the status bar.

Extra bonus: collapsible regions, delimited with the `{! #region !}` /  `{! #endregion !}` pair
![Jan-14-2020 09-25-27](https://user-images.githubusercontent.com/148698/72326949-75663d00-36b0-11ea-8bf4-c47d4cbc1f40.gif)

**Comment by fbricon** [comment]
@maxandersen @mkouba you can [try](https://github.com/redhat-developer/vscode-quarkus/#contributing) the latest CI build from https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/?C=M;O=D.

I tested https://github.com/quarkusio/quarkus-quickstarts/tree/master/qute-quickstart, renamed the templates to use the qute.html prefix then had to modify the Template injection points to
```java
    @Inject
    @ResourcePath("hello.qute")
    Template hello;
```

and 
```java
    @Inject
    @ResourcePath("items.qute")
    Template items;
```
