### ISSUE TITLE
[Qute] Add language configuration for Qute syntax

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-quarkus#183]
Add a language configuration for Qute to manages matching bracket, comments etc like I had done with Freemarker in https://github.com/angelozerr/lsp4e-freemarker/blob/master/org.eclipse.lsp4e.freemarker/language-configurations/language-configuration.json

This language configuration could be used in Eclipse IDE too with TM4E  /cc @jeffmaury

**Comment by fbricon** [comment]
closing as duplicate of #182
