### ISSUE TITLE
Show artifactId in the extensions picker

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#197]
In the Quarkus guides, sometimes, extensions are referred to by the groupId + artifactId. 

Examples:
https://quarkus.io/guides/kubernetes#add-readiness-and-liveness-probes
https://quarkus.io/guides/kubernetes#using-the-kubernetes-client
https://quarkus.io/guides/flyway#setting-up-support-for-flyway
https://quarkus.io/guides/qute#hello-world-with-jax-rs

Currently, the extensions picker does not display the groupdId or the artifactId, making it hard to identify which extensions the guides are referring to.

The artifactId was displayed before this PR: https://github.com/redhat-developer/vscode-quarkus/pull/165. It would be nice if we brought back the artifactId.

The extensions picker currently looks like this:
![image](https://user-images.githubusercontent.com/20326645/73010170-e65bd200-3ddf-11ea-8c5c-f2ffd4308ca8.png)

**Comment by xorye** [comment]
How does this look? In the gif, I am showing the artifactId when showing extension descriptions in place of the extension category:
![Pick extensions demo with artifactId](https://raw.githubusercontent.com/xorye/gifs/master/new_issues/artifactId.gif?token=AE3CR5ODR4HFW24TPKW3ATS6GNVOC)

**Comment by fbricon** [comment]
@xorye your image is missing

**Comment by xorye** [comment]
@fbricon it was a gif, does it work now?

Here is an image instead:
![image](https://user-images.githubusercontent.com/20326645/73033677-c5f83b80-3e10-11ea-8ddc-6a878fcc9d76.png)

**Comment by xorye** [comment]
![image](https://user-images.githubusercontent.com/20326645/73033946-90a01d80-3e11-11ea-83b5-0eef9b7748b8.png)

**Comment by xorye** [comment]
@fbricon what do you think about this?

![demo gif](https://raw.githubusercontent.com/xorye/gifs/master/new_issues/extension_picker/picker.gif?token=AE3CR5ONFUFSJFL665JISZS6Q5INW)

Here are some other options I explored:

Example A
![image](https://user-images.githubusercontent.com/20326645/77770052-0b0c3a00-701b-11ea-8266-379916ce60ca.png)

Example B
![image](https://user-images.githubusercontent.com/20326645/77770113-2414eb00-701b-11ea-85a8-5a2835099488.png)

Example C
![image](https://user-images.githubusercontent.com/20326645/77770159-355df780-701b-11ea-92ac-c0c1f4659113.png)

Example D
![image](https://user-images.githubusercontent.com/20326645/77770202-4575d700-701b-11ea-8546-24be258b324e.png)

Example E
![image](https://user-images.githubusercontent.com/20326645/77770238-532b5c80-701b-11ea-84af-7f1b58666c42.png)

**Comment by xorye** [comment]
IMHO I think the first gif seems pretty solid because it shows both groupId and artifactId (does it look to bloaty having both?) and still shows the category (Data, Messaging, Integration etc.) when you click on the icon on the top right corner

Having the groupId/artifactId and the category at the same time seems a bit messy.

It would be great if the detail section (the grey line underneath the extension name) could support newlines, but it seems like that's not possible. If we could put newlines, we could maybe put groupid/artifact in its own line.

**Comment by fbricon** [comment]
Yeah 1st example is the best. Allows you to toggle between light and bloaty but informative descriptions
