### ISSUE TITLE
Quarkus: Generate a Quarkus quickstart project command

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#200]
A new vscode-quarkus command called `Quarkus: Generate a Quarkus quickstart project`, which allows you to select a project from https://github.com/quarkusio/quarkus-quickstarts to download and open would be nice.

**Comment by fbricon** [comment]
Would be best if the code.quarkus.io backend provided an API for that, instead of requiring every tool to perform the git clone + extracting the matching folder

**Comment by datho7561** [comment]
I think that has been addressed through the Code Quarkus API. Starter code is added to the project based on which extensions are included. In #322, I added a step to the project generator to disable adding starter code.
