### ISSUE TITLE
Add extension for gradle project doesn't work on Windows OS

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-quarkus#214]
I try to reproduce the [issue 211](https://github.com/redhat-developer/vscode-quarkus/issues/211) on my Windows OS.

1. Open the `quarkus-gradle-project` that we use for our test.
3. Call the `Quarkus: Add extensions to current project` command
4. Add an extension (ex. Agroal)

Terminal falis with:

```
Execution failed for task ':addExtension'.
> Could not find quarkus-universe-bom-1.2.0.Final.json (io.quarkus:quarkus-universe-bom:1.2.0.Final).
  Searched in the following locations:
      file:/C:/Users/azerr/.m2/repository/io/quarkus/quarkus-universe-bom/1.2.0.Final/quarkus-universe-bom-1.2.0.Final.json
```

**Comment by xorye** [comment]
I am getting a different problem when trying to add an extension to that project on Windows 10:
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

**Comment by angelozerr** [comment]
Our `quarkus-gradle-project` is used for test and I suppose it misses some files. 

That's why I tried to create a project from scratch with vscode-quarkus command and add a new extension and it works pretty well.

I close this issue.
