### ISSUE TITLE
Failure to access API endpoint is not handled properly

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#22]
If the endpoint is not accessible when generating a new project, the wizard just waits endlessly despite an error being reported in the logs:
```
rejected promise not handled within 1 second: StatusCodeError: 404 - "RESTEASY003210: Could not find resource for full path: http://quarkus-generator.6923.rh-us-east-1.openshiftapps.com/extensions"
extensionHostProcess.js:759
stack trace: StatusCodeError: 404 - "RESTEASY003210: Could not find resource for full path: http://quarkus-generator.6923.rh-us-east-1.openshiftapps.com/extensions"
```

**Comment by fbricon** [comment]
An error message should surface to the user, the wizard should close

**Comment by xorye** [comment]
In settings.json, does the `quarkus.tools.starter.apiUrl` config point to the old url?

**Comment by xorye** [comment]
But I agree, there should be an error message if the endpoint is not accessible.

**Comment by fbricon** [comment]
it was, maybe because saving the last used values saved everything
