### ISSUE TITLE
When pasting, the comments gets duplicated when "editor.formatOnPaste":true

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer/vscode-quarkus#220]
When using Quakrus Properties mode , I see the comments in the properties file gets duplicated on copy paste and I have to press Ctrl+z to get them away.

![2020-02-28_20-09-19 (2)](https://user-images.githubusercontent.com/947745/75558836-6ec93480-5a68-11ea-87ee-c15b50312b2c.gif)

CC: @fbricon

**Comment by kameshsampath** [comment]
@fbricon  - as discussed on the chat I saw it came from SB plugin and when I uninstalled it it went away.

Thank you.

**Comment by kameshsampath** [comment]
I see see it . Sorry about the confusion.  All starts after  the Quarkus Welcome thing comes in vscode

**Comment by kameshsampath** [comment]
My current extensions
```alphabotsec.vscode-eclipse-keybindings
AndrsDC.base16-themes
DavidAnson.vscode-markdownlint
EditorConfig.EditorConfig
googlecloudtools.cloudcode
Gruntfuggly.todo-tree
joaompinto.asciidoctor-vscode
ms-azuretools.vscode-docker
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-vscode.Go
ms-vscode.sublime-keybindings
octref.vetur
redhat.apache-camel-extension-pack
redhat.atlasmap-viewer
redhat.java
redhat.project-initializer
redhat.vscode-apache-camel
redhat.vscode-camelk
redhat.vscode-openshift-connector
redhat.vscode-quarkus
redhat.vscode-wsdl2rest
redhat.vscode-xml
redhat.vscode-yaml
sdras.night-owl
streetsidesoftware.code-spell-checker
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscode-icons-team.vscode-icons
yzhang.markdown-all-in-one
zhuangtongfa.material-theme```

**Comment by kameshsampath** [comment]
Props 
```%dev.quarkus.log.console.color=false
## Step 5 ## 
# spring.datasource.url=jdbc:postgresql://192.168.64.22:32490/demodb
quarkus.datasource.url=jdbc:postgresql://192.168.64.23:31833/demodb
# spring.datasource.username=demo
quarkus.datasource.username=demo
# spring.datasource.password=password!
quarkus.datasource.password=password!
# spring.datasource.driver-class-name=org.org.postgresql.Driver
quarkus.datasource.driver=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=create-drop
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.datasource.max-size=8 
quarkus.datasource.min-size=2```

**Comment by kameshsampath** [comment]
@fbricon  - I found the root cause of the issue, it happens when you enable `"editor.formatOnPaste": true` setting.  You can simulate it by installing "sublime keymap" extension and then it ask to import all settings and one time is format on copy paste.  When make it false it works as expected.

**Comment by fbricon** [comment]
@kameshsampath thanks for the hint, I managed to reproduce this issue, it'll be easier to fix now, hopefully

**Comment by fbricon** [comment]
There's no need to install the sublime keymap BTW

**Comment by angelozerr** [comment]
Thanks @kameshsampath for having take time to give us valuable information.

I can reproduce it. It's a problem on the MicroProfile LS side with range formatting. I'm working on that....

**Comment by fbricon** [comment]
In the meantime, you can workaround the issue by adding this to your VS Code settings: 
```
"[quarkus-properties]":{
    "editor.formatOnPaste": false
},
"[microprofile-properties]": {
    "editor.formatOnPaste": false
},
```

**Comment by angelozerr** [comment]
@fbricon @kameshsampath please review my PR https://github.com/redhat-developer/quarkus-ls/pull/233 which should fixe this issue.

The bug occured when there have comments lines before the pasted content. Line comments was copied/pasted too.
