### ISSUE TITLE
[Qute] Syntax coloration problem with quote

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-quarkus#221]
Take the following Qute template:

```
{#if (condition)}
 'aaaaaaaa'
{/if}

{#if (condition) }
 'aaaaaaaa'
{/if}

{#if (condition) }
 'aaaaaaaa
{/if}

```

Here a screenshot which shows in action quote problem (see the last if):

![image](https://user-images.githubusercontent.com/1932211/75894186-25942e80-5e34-11ea-81af-ae3f380d5bc8.png)

It seems when there is no space between ')' and '}' the `aaaaaaaa` which is a text is not be considered as string (it's OK) but when there is a a space `aaaaaaaa`  is considered as string which is wrong.

**Comment by xorye** [comment]
This textmate grammar issue is easy to fix. Here is a related issue about having whitespaces before  the `}`. https://github.com/quarkusio/quarkus/issues/8158
