### ISSUE TITLE
Improve application.properties TextMate grammar

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#233]
There are pros and cons between the old textmate grammar and the new textmate grammar introduced in https://github.com/redhat-developer/vscode-quarkus/pull/230

Here are some cases where the two grammars act differently.
### Multiline property keys (old grammar is preferable):
Old grammar:
![image](https://user-images.githubusercontent.com/20326645/76900070-0d2e0600-686f-11ea-9254-6a51407aa6f3.png)

New grammar:
![image](https://user-images.githubusercontent.com/20326645/76900448-bf65cd80-686f-11ea-8e95-a7d580fc52e8.png)

### Multiline property values (new grammar is preferable):
Old grammar:
![image](https://user-images.githubusercontent.com/20326645/76900254-6007bd80-686f-11ea-94e9-544cb9a4e2f2.png)

New grammar:
![image](https://user-images.githubusercontent.com/20326645/76900542-ecb27b80-686f-11ea-9f17-91f1d37f4280.png)

### Apostrophes (old grammar is preferable):
Old grammar:
![image](https://user-images.githubusercontent.com/20326645/76900207-48303980-686f-11ea-86b8-80278e61d2a4.png)

New grammar:
![image](https://user-images.githubusercontent.com/20326645/76900616-123f8500-6870-11ea-89d1-30359f9c7d60.png)

For the new grammar, the issue about the apostrophes is here: https://github.com/textmate/ini.tmbundle/issues/3 and the PR that fixes seems to fix that issue is here: https://github.com/textmate/ini.tmbundle/pull/1

I've thought of three approaches we can take (please, by all means, suggest more approaches if there are better ones). The approaches are in no particular order.

To satisfy the cases above, we can either :
* Go back to the old grammar and build on top of it

OR

* Create issues in VS Code's repository to fix the grammars

OR

* Build on top of the VS Code's grammar ourselves since 2. might take a long time

**Comment by angelozerr** [comment]
There is a problem with the current TextMate grammar with property key when property has slash:

```
org.acme.restclient.CountriesService/mp-rest/url=https://restcountries.eu/rest
configKey/mp-rest/url = 
```

![image](https://user-images.githubusercontent.com/1932211/77149394-c4a26280-6a91-11ea-9792-7adf9fb8cadc.png)

**Comment by xorye** [comment]
@angelozerr I have now fixed that problem in my PR. If you have time, please try it out
