### ISSUE TITLE
Excluding unknown properties from validation no longer work

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#237]
With the latest code from master (server & extension),  excluding unknown org.acme.restclient.CountriesService/mp-rest/url=https://restcountries.eu/rest no longer clears the validation issue:
![Mar-27-2020 12-58-48](https://user-images.githubusercontent.com/148698/77753973-c1c3e680-702a-11ea-9559-206294c4822b.gif)

**Comment by angelozerr** [comment]
@xorye if you have time, could you see this bug issue please?

**Comment by xorye** [comment]
Yes, I can take a look at this

**Comment by xorye** [comment]
I made a PR to this issue here: https://github.com/redhat-developer/quarkus-ls/pull/284
