### ISSUE TITLE
Bad performance when working with non Quarkus/MP projects

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#240]
When opening https://github.com/eclipse/lemminx in vscode, I see jdt.ls receiving a ton of microprofile related requests. The UX suffers a lot, I experienced some really really bad lag in overall responsiveness

**Comment by angelozerr** [comment]
@fbricon even if I agree that we should limit the call of code action, code lens, etc for MP if project is not a MP project, I cannot reproduce your problem.

Could you please give me your usecase (with a little demo for instance to see your problem). Thanks!
