### ISSUE TITLE
Spawn vscode-microprofile extension out of vscode-quarkus 

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#248]
See https://github.com/redhat-developer/quarkus-ls/issues/268

Question : where should the new extension live?

**Comment by angelozerr** [comment]
I suggest that you see my PR for vscode-xml java extension https://github.com/redhat-developer/vscode-xml/pull/193/files

**Comment by angelozerr** [comment]
Remove all features managed by https://github.com/redhat-developer/vscode-microprofile (like all LSP features) and extend the vscode-microprofile with Quarkus support:

 * with Quarkus JDT
 * for Quarkus LS

by registering the proper JAR with package.json

It should be nice to update README and CONTRIBUTING to explain that vscode-quarkus is based on vscode-microprofile

**Comment by fbricon** [comment]
The vscode-microprofile extension lives at https://github.com/redhat-developer/vscode-microprofile
