### ISSUE TITLE
completion ignores already typed content

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#25]
If application.properties contains `quarkus.application.nam`, after typing `e` and selecting the matching entry, the whole key is appended after the original prefix:
![Aug-08-2019 17-41-13](https://user-images.githubusercontent.com/148698/62717213-c6884b80-ba03-11e9-9b44-3f394cbf6b68.gif)

**Comment by angelozerr** [comment]
This bug was fixed in https://github.com/redhat-developer/quarkus-ls/pull/34/files#diff-2d88ab14936172bf17bc4f9c8387a770R135 by using range.
