### ISSUE TITLE
qds snippet creates an invalid prop. for 1.5

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer/vscode-quarkus#255]
Currently when using the `qds` it generates an invalid url property.

Instead of `quarkus.datasource.jdbc.url` it creates `quarkus.datasource.url` which is not valid anymore.

**Comment by xorye** [comment]
Here is a PR that would fix this issue: https://github.com/redhat-developer/quarkus-ls/pull/317

**Comment by fbricon** [comment]
Fixed with redhat-developer/quarkus-ls#317
