### ISSUE TITLE
Improvements to javaServerStarter

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#257]
Currently, we get VM arguments from the `xml` configuration, which is a problem.
(huge thanks to @rzgry  for pointing this out):

https://github.com/redhat-developer/vscode-quarkus/blob/d0f285391c88e690416c37446cf18cb0a48c3c2f/src/languageServer/javaServerStarter.ts#L33

Next, it would be great if these issues addressing vscode-xml could be applied to vscode-quarkus:
* https://github.com/redhat-developer/vscode-xml/pull/266
* https://github.com/redhat-developer/vscode-xml/issues/257

**Comment by rzgry** [comment]
This has all been added to vscode-microprofile language server starter so I think this can be closed.
https://github.com/redhat-developer/vscode-microprofile/blob/master/src/languageServer/javaServerStarter.ts

**Comment by fbricon** [comment]
Fixed in 1.7.0
