### ISSUE TITLE
Add a trace.server configuration property

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#26]
Add a configuration property configurable in VSCode settings to view verbose language server communication mesasges.

A good reference [package.json](https://github.com/redhat-developer/vscode-xml/blob/35c122edcce09038e853dfab112dd76813302034/package.json#L72-L82) in vscode-xml.

**Comment by fbricon** [comment]
You need to choose a proper server name, see https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#logging-support-for-language-server
