### ISSUE TITLE
Add welcome page icon

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#260]
It seems VS Code 1.46 supports providing an icon for the webview tab: https://github.com/microsoft/vscode/blob/6af2987903c22bf9b19762d589bc46d4be636dc4/src/vs/vscode.d.ts#L6769

It would be nice if we had the Quarkus logo or something similar as the icon. Currently, the we have the default icon:
![image](https://user-images.githubusercontent.com/20326645/84390574-c62d8380-abc5-11ea-919c-5b2a9846f5f6.png)

**Comment by fbricon** [comment]
Most likely we'd need a monochrome icon, that either works for dark and light themes, or 2 monochrome icons. Dunno if the Quarkus project has that kind of asset we could reuse. ping @maxandersen

**Comment by maxandersen** [comment]
https://design.jboss.org/quarkus/

There are at least a monochrome one.

**Comment by fbricon** [comment]
New icons:

![WelcomePageIconDark](https://user-images.githubusercontent.com/22376627/85779086-3de4cd80-b6f1-11ea-947a-237c7c790f9e.png)

![WelcomePageIconLight](https://user-images.githubusercontent.com/22376627/85779091-3f15fa80-b6f1-11ea-8654-48b17b6be1ec.png)
