### ISSUE TITLE
Release of 1.6.0

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer/vscode-quarkus#265]
Hi mates, any chance to know when 1.6.0 is going to be released? I am asking because nowadays I am doing a lot of presentation about Quarkus and because of the change on the datasource jdbc property in Quarkus 1.5.0, I always need to explain why the snippet provided by Quarkus plugin is not valid. (https://github.com/redhat-developer/vscode-quarkus/issues/255)

Thanks :)

**Comment by angelozerr** [comment]
> Hi mates, any chance to know when 1.6.0 is going to be released? 

We will discuss about that with @fbricon this week.

> I always need to explain why the snippet provided by Quarkus plugin is not valid.

You can install the current vscode-quarkus at

https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/?C=M;O=D

**Comment by angelozerr** [comment]
1.6.0 has been released since several weeks.
