### ISSUE TITLE
PanacheEntity at creation time

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer/vscode-quarkus#275]
When I create a new `.java` file I can choose between several options (i.e `class`, `interface`, `enum`, ... [1]) if it is possible (don't know if it can be done) it will be nice to have a panache option too, so the generated class also implements `PanacheEntity`.

<img width="563" alt="Screenshot 2020-07-03 at 11 21 11" src="https://user-images.githubusercontent.com/1517153/86454332-5f603d80-bd1f-11ea-8cbd-6b0236f9185f.png">

**Comment by angelozerr** [comment]
I'm not sure that JDT LS provides this extension kind to customize option. @fbricon can you confirm that?

**Comment by fbricon** [comment]
no we can't do that. It might even be pretty tricky to add
