### ISSUE TITLE
Java 11 notification popup: extension does not detect Java-11

### ISSUE THREAD

**Issue by zemiak** [redhat-developer/vscode-quarkus#286]
Hello,

I constantly get a Java 11 notification popup at vscode startup. However, I have installed Java 11:
```
    "java.configuration.runtimes": [
    
        {"name": "JavaSE-1.8", "path": "/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home"},
        {"name": "JavaSE-11", "path": "/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home"}
    ]
```

```
$ /usr/libexec/java_home -v11  
/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
$ ls /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin
jaotc       java        javap       jdb         jfr         jinfo       jmap        jrunscript  jstat       pack200     rmiregistry
jar         javac       jcmd        jdeprscan   jhsdb       jjs         jmod        jshell      jstatd      rmic        serialver
jarsigner   javadoc     jconsole    jdeps       jimage      jlink       jps         jstack      keytool     rmid        unpack200
```

My default JAVA_HOME in the system is Java8, but my expectation is, that the extension should be able to read the JDK configuration from vscode settings.

Thanks

**Comment by fbricon** [comment]
"java.configuration.runtimes" lists all the runtimes to compile your projects. 
The message you see is about the runtime used to **run** the Java Language server. It will use JAVA_HOME by default (1.8 in your case), but you can override it by setting the `java.home` preference in vscode

**Comment by zemiak** [comment]
OK, after setting java.home, there are no popups anymore. It was not clear, what to do from the popup message.
Thanks for help.

**Comment by angelozerr** [comment]
> OK, after setting java.home, there are no popups anymore. It was not clear, what to do from the popup message.

@zemiak which kind of message you wanted to have for a best understand of the problem?

**Comment by zemiak** [comment]
@angelozerr 
The current text says: "Java 11 or more recent is required to run 'Quarkus Tools for Visual Studio Code'. Please download and install a recent JDK."

Minimalistic solution: add the following sentence " Set the java.home property in the settings to your Java 11 home."

Optimal solution: extension should detect the JavaSE-11 or better from java.configuration.runtimes and set the java.home if it's empty.

**Comment by angelozerr** [comment]
@zcervink thanks for your feedback.

@fbricon I reopen the issue in order to improve that.

**Comment by rgrunber** [comment]
Should be easy to fix the notification issue.

Regarding `java.configuration.runtimes`. This issue should become much less common because vscode-java now ships a JDK (currently Java 17 on most common platform/archs), and extensions like vscode-microprofile & vscode-quarkus do attempt to use it, if it exists.

if user defines a JDK in `java.configuration.runtimes` that we do not detect (whether through find-java-home or jdk-utils) and it is the only JDK that meets the requirements to run successfully ( >= 11), couldn't we just read use it and save the user some hassle ? This would probably be done on the vscode-java side.

**Comment by rgrunber** [comment]
I think we need to close this issue as using `java.configuration.runtimes` to find a JDK compliant with the Quarkus extension is unlikely to happen. There were a few discussions in vscode-java about doing this, but ultimately, that setting is not meant to be used for that. The good news is jdk-utils should detect many possible candidates on the system, and for most common platforms, vscode-java ships with a JDK that is compatible, which the Quarkus tooling can also use.

**Comment by rgrunber** [comment]
Whoops, let's at least adopt the "Minimalistic solution" . Update the notification message.

**Comment by rgrunber** [comment]
After some more discussion, I'm closing this. @JessicaJHee correctly pointed out that vscode-java should correctly handle the Java runtime detection. I still think there could be some slight improvements made by migrating to jdk-utils but we can always handle those separately.
