### ISSUE TITLE
Investigate why `quarkus-properties` appears twice when registering `textDocument/rangeFormatting`

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#296]
In the 1.6.0 release (before the vscode-microprofile / vscode-quarkus split), when opening a Quarkus application.properites file, 
looking at the server trace, `quarkus-properties` appears twice in the `client/registerCapability` request for range formatting;

```
[Trace - 11:16:26 a.m.] Received request 'client/registerCapability - (8)'.
Params: {
    "registrations": [
        {
            "id": "61e7b5ba-a567-4415-8817-70e18fed36a9",
            "method": "textDocument/rangeFormatting",
            "registerOptions": {
                "documentSelector": [
                    {
                        "language": "microprofile-properties"
                    },
                    {
                        "language": "quarkus-properties"
                    },
                    {
                        "language": "quarkus-properties"
                    }
                ]
            }
        }
    ]
}
```

It's strange that `quarkus-properties` appears twice, although I couldn't find any bugs because of this. Range formatting still works as expected.

**Comment by datho7561** [comment]
[This line here in quarkus-ls](https://github.com/redhat-developer/quarkus-ls/blob/master/quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/QuarkusRegistrationConfiguration.java#L31) is likely contributing the extra occurrence of `quarkus-properties`.
