### ISSUE TITLE
Generating a Gradle project without adding any extra extensions adds duplicate entry in build.gradle

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#298]
After generating a Gradle project without any extra extensions added using the `Quarkus: Generate a Quarkus project` command:

![image](https://user-images.githubusercontent.com/20326645/89342348-a91aab80-d670-11ea-93b9-fe2ea60d22c4.png)

In the newly generated project, `implementation 'io.quarkus:quarkus-resteasy'` appears twice:
![image](https://user-images.githubusercontent.com/20326645/89342410-c0599900-d670-11ea-83bc-322b25f8f7ee.png)

It should only appear once.

This issue probably happens because the RESTEasy JAX-RS extension (the required extension) exists in `state.extensions` here: https://github.com/redhat-developer/vscode-quarkus/blob/f38f4caaf218cf9c6ce91e64a0d9cd632314a483/src/wizards/generateProject/ExtensionsPicker.ts#L150

**Comment by datho7561** [comment]
I can't reproduce this issue; it must have been fixed upstream, either in the [Quarkus Gradle extension](https://github.com/quarkusio/quarkus/tree/master/devtools/gradle) or the [Quarkus project generator service/website](https://github.com/quarkusio/code.quarkus.io). ~~I am looking for the corresponding PR.~~
