### ISSUE TITLE
Debug quarkus project command doesn't appear on Quarkus projects after going from lightweight mode to standard mode

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#299]
When the Java language server starts in lightweight mode, the project label info command (which is called when vscode-quarkus first starts) fails. Therefore the debug current quarkus project command (and add extensions command) will not appear in the command palette.

When the Java language server is switched to standard mode we still do not have those commands because the project labels command isn't triggered. The user would have to trigger it by adding or removing a workspace file: 
https://github.com/redhat-developer/vscode-quarkus/blob/f38f4caaf218cf9c6ce91e64a0d9cd632314a483/src/QuarkusProjectListener.ts#L38

**Comment by angelozerr** [comment]
@xorye have you some idea how to fix this issue?

**Comment by xorye** [comment]
Currently, the `microprofile/java/workspaceLabels` is called when vscode-quarkus first starts. Vscode-quarkus caches the result. Depending on the result (whether or not there are quarkus projects in the current workspace), vscode-quarkus will either display or hide the "Add quarkus extensions" and "Debug current quarkus project" commands from the command palette. If the Java LS is in lightweight mode, vscode-quarkus does not get a result for `microprofile/java/workspaceLabels`.

One solution would be to always show the "Add quarkus extensions" and "Debug current quarkus project" commands in the command palette if the Java language server is in lightweight mode. If the user calls one of these commands while in lightweight mode, I don't think vscode-quarkus should do anything to stop it since adding quarkus extensions and calling the debug command don't need to depend on the Java language server.

To do this, vscode-quarkus needs to know when the Java language server is in lightweight mode and when its in standard mode.

Lightweight mode -> always show  "Add quarkus extensions" and "Debug current quarkus project" commands
Standard mode -> keep the current functionality (shows/hide the  "Add quarkus extensions" and "Debug current quarkus project" commands depending on the result from `microprofile/java/workspaceLabels`)

The feature that shows/hides the  "Add quarkus extensions" and "Debug current quarkus project" commands is just an enhancement that depends on the Java language server. Since its an enhancement, I think we can live without it in lightweight mode.
