### ISSUE TITLE
Codestarts

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/vscode-quarkus#301]
@fbricon asked me to start a discussion on https://quarkus.io/blog/codestarts-preview/

If vscode-quarkus is using code.quarkus.io/api, codestarts will be activated by default in the backend, so nearly transparent on your side, changes: 
- new query param: `ne (no-example): boolean`
- ignored query params: `p (path)` and `c (class name)`

Any thoughts?

**Comment by ia3andy** [comment]
@maxandersen should we keep using `code.quarkus.io/api` from the IDEs tooling, or is it meant to change?

**Comment by maxandersen** [comment]
We won't have big changes here before code quarkus would get codestarts thus fine to add these two options.

**Comment by fbricon** [comment]
So that's the equivalent to toggling Example Code right?

<img width="729" alt="Screenshot 2020-11-20 at 10 00 12" src="https://user-images.githubusercontent.com/148698/99780880-64c7f400-2b17-11eb-8529-a7f25d82f4ee.png">

**Comment by ia3andy** [comment]
@fbricon yes! 

FYI we decided to keep using the group-id as package-name, the api will not change, only the generated apps.
