### ISSUE TITLE
Quarkus Tools doesn't work

### ISSUE THREAD

**Issue by dominwong4** [redhat-developer/vscode-quarkus#308]
1.
the preview url doesn't show
![image](https://user-images.githubusercontent.com/13159792/94653043-87b30480-032d-11eb-8086-1ea4076688c5.png)

2.
command P doesn't work, just showing activating extensions at the left bottom corner and nothing comes out
![image](https://user-images.githubusercontent.com/13159792/94653017-7a961580-032d-11eb-8872-69e62d7e309e.png)

3.
No add extensions command inside a Quarkus project 

![image](https://user-images.githubusercontent.com/13159792/94653230-d2cd1780-032d-11eb-8551-1382dc0b1664.png)

Anyway to fix it?

**Comment by fbricon** [comment]
Did the Java Language server start in Standard mode? You should see a thumb up in the lower right corner of vscode
Can you see anything in the Output view > Language Support for Java, and Output view > Tools for MicroProfile?

**Comment by dominwong4** [comment]
![image](https://user-images.githubusercontent.com/13159792/94655048-918a3700-0330-11eb-9de1-c8edb7c88fed.png)
so is that mean my Language Support for Java is not working properly?

**Comment by dominwong4** [comment]
> Did the Java Language server start in Standard mode? You should see a thumb up in the lower right corner of vscode
> Can you see anything in the Output view > Language Support for Java, and Output view > Tools for MicroProfile?

thanks,
I fixed it. I found a solution in your past repo
[https://github.com/redhat-developer/vscode-java#setting-the-jdk](https://github.com/redhat-developer/vscode-java#setting-the-jdk)

thx a lot
