### ISSUE TITLE
`quarkus.hibernate-orm.database.generation` values should be enumerated

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#317]
Currently `quarkus.hibernate-orm.database.generation` provides no completion for its possible values. We should see `none`, `create`, `drop-and-create`, `drop`, `update`.

<img width="644" alt="Screenshot 2020-11-01 at 18 17 27" src="https://user-images.githubusercontent.com/148698/97809664-8cd9db00-1c6e-11eb-8ea9-0d530530a2cd.png">

You can see an example in https://github.com/fbricon/quarkus-spread-poll/blob/master/src/main/resources/application.properties#L19

**Comment by angelozerr** [comment]
To fix this issue, we should declare on quarkus-ls an hints for this property like https://github.com/eclipse/lsp4mp/blob/ab86a54e2be98c20ada1664ce910a015779c6b4d/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/static-properties/mp-opentracing-metadata.json#L31

**Comment by angelozerr** [comment]
Like Spring Boot does https://github.com/spring-projects/spring-boot/blob/a8705d19e59c6ab0a8555c079e59995aad395210/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L1871

**Comment by angelozerr** [comment]
This issue should be very easy to do.
