### ISSUE TITLE
"Debug current Quarkus Project" command does nothing

### ISSUE THREAD

**Issue by lorthirk** [redhat-developer/vscode-quarkus#324]
Tried with the quickstart on both a Windows + WSL setup and a MacOS native. running `./mvnw quarkus:dev` manually starts the dev server and everything is fine.

Is there anything I can do to provide some log?

**Comment by lorthirk** [comment]
Ok, despite knowing nothing about VSCode extensions I tried to debug it. Apparently I found something, don't know how useful.

The issue seems to reside here:

https://github.com/redhat-developer/vscode-quarkus/blob/8ccbb31e2f89571ab25b6b47eea310a8953bb858/src/utils/tasksUtils.ts#L68-L75

In my case, `task.execution` is `undefined`. Apparently this could be a valid state, since in `@vscode/index.d.ts` the `Task` class has

```
/**
 * The task's execution engine
 */
execution?: ProcessExecution | ShellExecution;
```

In my case, just checking that `execution` is not `undefined` prior to the other checks seems to fix the issue. I'm not proposing a PR because I honestly have no clue in how this can affect the whole functionality, but I hope someone more familiar than me with the extension can start from here.

This is the definition of the only `Task` available on my environment:

```
{
  "__deprecated": false,
  "_definition": {
    "type": "java",
    "label": "java: exportjar:quarkus-cookbook",
    "targetPath": "${workspaceFolder}/${workspaceFolderBasename}.jar",
    "elements": [
      "${compileOutput}",
      "${dependencies}"
    ]
  },
  "_scope": {
    "uri": {
      "$mid": 1,
      "fsPath": "/home/lorthirk/git/lorthirk/quarkus-cookbook",
      "external": "file:///home/lorthirk/git/lorthirk/quarkus-cookbook",
      "path": "/home/lorthirk/git/lorthirk/quarkus-cookbook",
      "scheme": "file"
    },
    "name": "quarkus-cookbook",
    "index": 0
  },
  "_name": "exportjar:quarkus-cookbook",
  "_source": "java",
  "_problemMatchers": [],
  "_hasDefinedMatchers": true,
  "_isBackground": false,
  "_presentationOptions": {
    "echo": true,
    "reveal": 3,
    "revealProblems": 1,
    "focus": false,
    "panel": 1,
    "showReuseMessage": true,
    "clear": false
  },
  "_runOptions": {},
  "__id": "vscjava.vscode-java-dependency.elements,0,${compileOutput},1,${dependencies},,label,java: exportjar:quarkus-cookbook,targetPath,${workspaceFolder}/${workspaceFolderBasename}.jar,type,java,"
}
```

**Comment by lorthirk** [comment]
Another hint: the task that causes the issue comes from [Project Manager for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency). Disabling this extension fixes the issue. But I honestly think the fix should be done in the Quarkus extension.

**Comment by datho7561** [comment]
Looks like the solution you proposed works. AFAIK when vscode-quarkus makes the Task, it defines this field https://github.com/redhat-developer/vscode-quarkus/blob/master/src/wizards/debugging/TaskCreator.ts#L106. Would you be able to open a PR for it? (If not I could)

**Comment by lorthirk** [comment]
Sure, I'll create the PR as soon as I get back to my PC.
