### ISSUE TITLE
No Quarkus projects were detected in this folder

### ISSUE THREAD

**Issue by jeanabraham** [redhat-developer/vscode-quarkus#358]
Hello,

I have a Quarkus project that runs when I do `mvn quarkus:dev`.

But when trying to debug from VSCode using the `Quarkus: Debug current Quarkus Project` command, I get this error:
```
No Quarkus projects were detected in this folder 
```

Do I need to add any additional metadata for the detection?

Thanks!

**Comment by angelozerr** [comment]
@jeanabraham is it possible to share your project?

**Comment by angelozerr** [comment]
@jeanabraham is it possible to share your project?

**Comment by jeanabraham** [comment]
@angelozerr Thanks, works now.  Seem to have been missing the below config:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "preLaunchTask": "quarkus:dev",
            "type": "java",
            "request": "attach",
            "hostName": "localhost",
            "name": "debug quarkus-project",
            "port": 5005
        }
    ]
}
```
