### ISSUE TITLE
Let users know they can deploy to openshift

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#359]
Once the new deploy to openshift command is available (#316),  we should promote the new feature 
- in the welcome page: https://github.com/redhat-developer/vscode-quarkus/blob/master/assets/webviews/templates/welcome.ejs
- by showing a popup (only once!), advertising the feature, once the user execute the debug command

**Comment by datho7561** [comment]
I'll take a look into doing this now that Deploy to OpenShift is merged
