### ISSUE TITLE
Adding an extension assumes the pom.xml is at the root of the folder

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#36]
When opening a folder `foo` containing a `bar` quarkus project, running the `add extension` command will execute `mvn quarkus:add-extension -Dextensions="some.extension"` in the `foo` directory instead of the `bar` one.
If the workspace contains multiple pom.xml files, then the command should propose the list of pom.xml to apply the change to, then execute the command (using the mvn wrapper if present) with the `-f path/to/selected/pom.xml` flag

**Comment by xorye** [comment]
When the currently opened directory contains multiple pom.xml files, currently I have this prompt appearing once the user selects which extensions to add:
![image](https://user-images.githubusercontent.com/20326645/63542963-ac646800-c4ef-11e9-91b8-138093a49195.png)

The options display the absolute path to the pom file.

One thing that I think should be gone is the text box. 

@fbricon @angelozerr what are your thoughts?
