### ISSUE TITLE
Generated source from grpc protobuf missing from classpath (gradle)

### ISSUE THREAD

**Issue by fdasoghe** [redhat-developer/vscode-quarkus#361]
Started with a fresh new project (gradle based) with grpc support. 

All gradle tasks works as expected: generated code is put in `build/classes/java/quarkus-generated-sources/grpc` (task `quarkusGenerateCode`), build is working and app is starting (task `quarkusDev`).

But in VSCode generated classes are not visible, as if they were out of compile classpath. It looks like the quarkus-vscode-gradle tooling is missing something somewhere?

VSCode 1.52.2
Gradle 6.8.3
vscode-quarkus 1.8.0

UPDATE: as a workaround, I did this:

```
sourceSets {
    main {
        java {
            srcDirs layout.buildDirectory.dir("classes/java/quarkus-generated-sources/grpc")
        }
    }
}
```

**Comment by rgrunber** [comment]
I'm able to reproduce as well on a simple Gradle project with grpc from https://code.quarkus.io/ and a protobuf file from https://quarkus.io/guides/grpc-getting-started . However, simply changing from Gradle to Maven works, so maybe this is a JDT-LS (specifically buildship) issue. It certainly works on the command line for the Gradle case.

@fbricon @snjeza thoughts ?

**Comment by snjeza** [comment]
You can try the following build.gradle:

```
plugins {
... 
    id 'eclipse'
...
}
...
eclipse {
    classpath {
        containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
        file.whenMerged { cp ->
            def entries = cp.entries;
            def src = new org.gradle.plugins.ide.eclipse.model.SourceFolder('quarkus-generated-sources/grpc', null)
            entries.add(src)
        } 
    }
}
```
See https://github.com/eclipse/eclipse.jdt.ls/issues/1667#issuecomment-786101045

**Comment by HerrDerb** [comment]
Any news on that?

**Comment by angelozerr** [comment]
@rgrunber  @snjeza  It seems it is an issue with JDT-LS, right? Can we close it or transfer it?

**Comment by rgrunber** [comment]
I think we actually support this now, based on https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2189 . We have a setting in vscode-java (enabled by default) :

```json
"java.jdt.ls.protobufSupport.enabled": {
    "type": "boolean",
    "default": true,
    "markdownDescription": "Specify whether to automatically add Protobuf output source directories to the classpath.\n\n**Note:** Only works for Gradle `com.google.protobuf` plugin `0.8.4` or higher.",
    "scope": "window",
    "order": 80
},
```

**Comment by angelozerr** [comment]
Ok thanks @rgrunber for your answer.

I close the issue. @fdasoghe if you have again a problem,please report your issue at https://github.com/redhat-developer/vscode-java
