### ISSUE TITLE
Collect telemetry for which extensions are used

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-quarkus#364]
See https://github.com/redhat-developer/vscode-quarkus/pull/345#pullrequestreview-676365044.

It would be helpful to collect telemetry on which Quarkus extensions are being added to projects when "Quarkus: Add extensions to current project" (`quarkusTools.addExtension`) is being run. This would help us to focus our support on features for those extensions.

**Comment by rgrunber** [comment]
This was done in https://github.com/redhat-developer/vscode-quarkus/pull/437/files#diff-4fae9500233039607835a0ebb0641eb63e1d883938be0d2d32f4ebe64cbbb3e0R20 .
