### ISSUE TITLE
Update @redhat-developer/vscode-redhat-telemetry to 0.1.1

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-quarkus#365]
This removes the dependency to vscode-commons.

See https://github.com/redhat-developer/vscode-redhat-telemetry#add-the-below-code-to-your-extensionts for instructions on how to implement this change.

~~Note that `redhat.telemetry.enabled` doesn't need to be added to the `package.json`, since it will be contributed by vscode-java~~ see note from Fred

**Comment by fbricon** [comment]
not until java telemetry is rolled out. Until then vscode-microprofile should own it
