### ISSUE TITLE
Add support for configuration file per profile

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#371]
> The user can have an application.properties with general configuration and one file for each profile, like application-dev.profile for dev profile.

- https://github.com/quarkusio/quarkus/pull/11145

> Properties in the profile aware file have priority over profile aware properties defined in the main file.

- https://github.com/quarkusio/quarkus/issues/18292

**Comment by datho7561** [comment]
I've worked on eclipse/lsp4mp#149, which should make it easier to implement this feature. The PR also lets us implement the support for per profile config files in quarkus-ls, so that the base lsp4mp project doesn't need to support it.
