### ISSUE TITLE
Debugging no-starter code projects fails

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#389]
When creating a no-starter code project (you still need to create 1 java file), if you execute the debug quarkus command, the process never completes.
This is mostly caused by the quarkus dev task's problemMatcher.background.endspattern value, that expects a "listening on" pattern. 
https://github.com/redhat-developer/vscode-quarkus/blob/46b180ee55cbf71ccef64e04c90bdc273f3b7146/src/buildSupport/GradleBuildSupport.ts#L30

https://github.com/redhat-developer/vscode-quarkus/blob/46b180ee55cbf71ccef64e04c90bdc273f3b7146/src/buildSupport/MavenBuildSupport.ts#L30

When no http server is started, that last sentence is missing, it then just waits indefinitely.

Using `^.*Quarkus .* started in .*\\.*` works.

Also, it doesn't seem to cause an issue but when a Gradle deamon is reused, this pattern is never found:
https://github.com/redhat-developer/vscode-quarkus/blob/46b180ee55cbf71ccef64e04c90bdc273f3b7146/src/buildSupport/GradleBuildSupport.ts#L29

I'd simply use `Task :` instead

**Comment by rgrunber** [comment]
Yup, I can reproduce :

`2021-08-30 12:46:46,325 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-no-code 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.1.4.Final) started in 1.290s.`
