### ISSUE TITLE
Properties files with property expressions are flagged as wrong

### ISSUE THREAD

**Issue by jamesfalkner** [redhat-developer/vscode-quarkus#392]
For example, in my `application.properties` I have:

```properties
%prod.quarkus.datasource.username = ${DBUSER:sa}
```

In vscode, I get red squigglies:

![image](https://user-images.githubusercontent.com/861894/132564598-9045ad50-d878-4080-a67f-6d5c4df4af59.png)

And the hover tooltip says: 

![image](https://user-images.githubusercontent.com/861894/132564657-b07cb1be-3279-46e7-a0a4-284129a8012d.png)

Yet the app works as expected!

**Comment by angelozerr** [comment]
The expression validation is very basic,it checks that content of expression reference a property that you define in the properties file (ex : DBUSER:sa=XXXX). But in your case, it doesn't make sense.

The expression validation should be improved again. To remove this error, you can disable the expression validation like this:

`"microprofile.tools.validation.expression.severity": "none"`

or if you want to ignore validation only for quarkus.datasource.username, you can define in your settings:

`"microprofile.tools.validation.expression.excluded": ["quarkus.datasource.username"]`

I noticed that `microprofile.tools.validation.expression.excluded` is an unkwonw setting. I created a PR for that https://github.com/redhat-developer/vscode-microprofile/pull/71 

@AlexXuChen please review it.

**Comment by fbricon** [comment]
@angelozerr property expressions with a default value should not raise an error:
```
${expression:value} - Provides a default value after the : if the expansion doesn’t find a value.
```

See https://quarkus.io/guides/config-reference#property-expressions

**Comment by angelozerr** [comment]
>@angelozerr property expressions with a default value should not raise an error:

please create an issue. The original issue was about that expression property was not found.

**Comment by fbricon** [comment]
I disagree. Missing default property expression support is the root cause of this issue, that's why it's flagged as an error.

**Comment by angelozerr** [comment]
@fbricon I agree with you, default value should be supported, but even if we support it, we will have an error on `DBUSER` only.

I mean if you write just an expression without default value:

`%prod.quarkus.application.name = ${DBUSER}`

you have the same problem.

**Comment by angelozerr** [comment]
@jamesfalkner could you explain me where you declare the property `DBUSER`? In your pom.xml as inside `<properties>` or with https://quarkus.io/guides/datasource#named-datasource-injection ?

**Comment by jamesfalkner** [comment]
It's set in the environment and consumed at runtime to replace the value of ${DBUSER} with the value from the process's environment. (but it is very likely _not_ defined in the IDE's environment - it's just assumed it'll be defined at runtime in production - hence the default value is provided as well).

**Comment by angelozerr** [comment]
Thanks for your feedback. 

Perhaps we should give the capability to define in a settings the environement variable to support correctly the diagnostic support.

@fbricon @rgrunber what do you think about that?

**Comment by rgrunber** [comment]
I suppose we could expand `BuildSupport.ts` to also read some setting we define for adding more properties (through system/env), but it honestly doesn't seem like this is what's required. There's [plenty of ways](https://quarkus.io/guides/config-reference#configuration-sources) to provide properties so I'm not sure if providing yet another source through client settings changes anything.

Should we emit a diagnostic when we encounter a variable with no default value, where we can't detect a value at build time ? The warning could mention that they should ensure it is at least defined at runtime.

**Comment by angelozerr** [comment]
> It's set in the environment 

What is your configuration from https://quarkus.io/guides/config-reference#configuration-sources (System properties, Environment variables or .env)?

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lsp4mp/issues/201
