### ISSUE TITLE
textDocument/inlayHint fails when re-opening vscode on a qute template

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#503]
When the current editor is a qute template, if you restart vscode, you'll see an error popup, caused by textDocument/inlayHint  failure:

<img width="1904" alt="Screenshot 2022-05-18 at 11 28 33" src="https://user-images.githubusercontent.com/148698/169007125-da1c2eca-4d25-4243-a947-d100aeff9456.png">

 
> [Trace - 11:26:21 AM] Received response 'textDocument/inlayHint - (6)' in 1113ms. Request failed: The request (id: 6, method: 'textDocument/inlayHint') has been cancelled (-32800).
[Error - 11:26:21 AM] Request textDocument/inlayHint failed.
[object Object]

**Comment by angelozerr** [comment]
The client code for managing inlayHint is hosted in vscode quarkus but we should remove it and use last published of vscode languagclient which shout provide inlayHint.

The thing which I fear is that the current code is à copy paste of vscode languageclient.

Let migrate to vscide languageclient and see if it will fix this issue.

**Comment by angelozerr** [comment]
This issue should be fixed with https://github.com/redhat-developer/vscode-quarkus/pull/506
