### ISSUE TITLE
Syntax coloring problem

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-quarkus#57]
The syntax coloring seems not worked with `application.properties`, the key should be highlighted in blue:

![image](https://user-images.githubusercontent.com/1932211/64062084-fe3d7a00-cbe2-11e9-8bd4-3c652ae03760.png)

If I create a file like `test.properties`, the syntax coloring is correct:

![image](https://user-images.githubusercontent.com/1932211/64062122-48bef680-cbe3-11e9-9436-e57ac3b147ef.png)

**Comment by fbricon** [comment]
It's not that the syntax is incorrect, it's just that it's a different grammar, the same one used by spring tools.

**Comment by fbricon** [comment]
y guess is it's a way to distinguish XXX properties from regular properties

**Comment by angelozerr** [comment]
Thank's for the information @fbricon . It's not a bug.
