### ISSUE TITLE
Add a progress bar / visual clue when loading completion is too long

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#58]
Warming up the quarkus completion can take several seconds. It's unclear then, that something is happening. Users should get a visual clue enticing them to wait for a result. Whether it's a progress bar or a loading indicator in the task bar below, I guess it'll depend on what's technically  possible.

**Comment by jeffmaury** [comment]
I've tested with an empty P2 repo (in order to force download of deployment JARs during getProjectInfo) and a Quarkus application with all extensions: looks good on VSCode as the UI displays 'Loading' while waiting for the response. The only issue is that the request takes several minutes to process.

**Comment by angelozerr** [comment]
@jeffmaury we should indeed manage progress monitor on server side with clean steps. But to benefit with this feature we need progress support. Even if JDT LS has implemented custom progress we would like to use LSP progress to benefit with this feature with another LSP clients (Eclipse IDE and IJ for you).

To implement this issue, we need:

 * waits for LSP4J progress support https://github.com/eclipse/lsp4j/issues/370
 * once it will implement, LSP4E (cc @mickaelistria) will able to implement this LSP progress support
 * consume progress support on Quarkus LS when LSP4J will implement this support)

**Comment by jeffmaury** [comment]
Not sure to understand the workflow in this specific case as the long process is outside of the LS. But maybe I'm missing something

**Comment by angelozerr** [comment]
> as the long process is outside of the LS

Yes but according my understand, the call of `IProgressMonitor.worked(int work)` should generate an LSP progress notification.

**Comment by fbricon** [comment]
that's how it looks in vscode now:
![Jan-07-2020 17-17-26](https://user-images.githubusercontent.com/148698/71910157-b79ff380-3171-11ea-806e-5fb53abafc51.gif)
