### ISSUE TITLE
Request textDocument/documentSymbol failed in the Tools for MircroProfile VS Code extension

### ISSUE THREAD

**Issue by danieloh30** [redhat-developer/vscode-quarkus#640]
When I type in quarkus properties, the suggestion automatically shows but the MP error keeps showing in the output.

<img width="1277" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/84e5a8ce-50d2-41b9-88fe-57b4418fd107">

<img width="737" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/e480b669-8bfa-4f8a-a81c-f049166d8f23">

<img width="737" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/21478147-1abf-4af1-9194-9a7c840d3e32">

<img width="928" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/58923a1b-e62c-4b9c-aa2b-ed8f1e14a244">

**Comment by angelozerr** [comment]
I can reproduce the issue. The problem is when a property starts with `.` like 

`.a`

We split property with `.` and the first segment is empty and document segment (that it is used to fill outline and breadcrumbs) name is empty 

```json
[Trace - 12:43:26 PM] Received response 'textDocument/documentSymbol - (166)' in 3ms.
Result: [
    {
        "name": "",
        "kind": 4,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 2
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 2
            }
        },
        "children": [
            {
                "name": "a",
                "kind": 7,
                "range": {
                    "start": {
                        "line": 0,
                        "character": 0
                    },
                    "end": {
                        "line": 0,
                        "character": 2
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 0,
                        "character": 0
                    },
                    "end": {
                        "line": 0,
                        "character": 2
                    }
                },
                "children": []
            }
        ]
    }
]
```

vscode seems not like document symbol name which are empty. We need to take care of this problem.

**Comment by danieloh30** [comment]
Cool. Thanks for the quick confirmation. Hope it could be fixed easily and quickly :)
