### ISSUE TITLE
"Last Used" option is present in the filter results

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#7]
After invoking the "Generate a Maven project" or the "Add extensions to current project" command, during the step where the user selects extensions,  the "Last Used" option is present when filtering.
 
![image](https://user-images.githubusercontent.com/20326645/61460936-c08bd700-a93d-11e9-9bf6-3c73e99a845b.png)

**Comment by fbricon** [comment]
not sure this is fixable. See how the spring initializer extension deals with it

**Comment by xorye** [comment]
yep, turns out spring initializer doesn't deal with it

**Comment by fbricon** [comment]
Not a big deal. Closing.
