### ISSUE TITLE
Cannot select which project to debug when multiple workspace folders are open

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-quarkus#74]
Open multiple workspace folders containing Maven Quarkus projects  in VS Code like so:
```
project1/
project2/
project3/
```
Do not open any file (ensure there are no open editors), just have the folders loaded in VS Code.

When calling the debug command (Quarkus: Debug current Quarkus project), we currently do not know which Quarkus project should be debugged.

In this case, I propose to add an input box, similar to what we already have for the Add Extensions wizard:
![image](https://user-images.githubusercontent.com/20326645/64792575-a3434580-d547-11e9-8d67-569b8b9f9b16.png)
Something like that could help determine which Quarkus project to debug.

**Comment by raulvaldoleiros** [comment]
Please support this feature
