### ISSUE TITLE
defaults for quarkus new maven projects are not "proper"

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-quarkus#75]
- [x] (minor) Group id is "org.my.group" - suggestion: "org.acme" as used in quarkus getting started guide.
- [x] Instead of mixed case for project "MyQuarkusProject" use what is in quarkus default guides "getting-started" or "quarkus-getting-started". 
- [x] package name "PackageName" is mixed case where packages are normally lower case and prefixed. suggestion: use "org.acme" as in quarkus getting started guide or even better default to what user used for groupid.
- [x] Resource name would be better if could be "GreetingResource" as in Getting started guide.

**Comment by fbricon** [comment]
Yup, I was supposed to fix those, some time ago, bit it ended up in a git stash ;-)

**Comment by xorye** [comment]
@fbricon could I take care of this?

**Comment by fbricon** [comment]
sure
