### ISSUE TITLE
Validate initial input value, offer context on invalid values

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-quarkus#84]
When I run generate maven project the default value for artifact id is "MyQuarkusProject" and that gives two problems:

1) when pressing enter on it the wizard does not move forward nor does it highlight the artifact id is not allowed.
2) only when editing the field do you get an error highlighting the issue, but it just says "invalid artifact id" giving no hint on what is wrong - in this case seem to be that it has uppercase letters. 

So would be good to have the validation error shown immediately or at least when pressing Enter and then tell user what is actually wrong with the artifact id or say what a valid one would be.

**Comment by maxandersen** [comment]
![2019-09-19_11-10-29 (1)](https://user-images.githubusercontent.com/54129/65230657-8621f000-dace-11e9-8760-50e7a740eaf7.gif)

here is me showing validation not showing up before I edit the value. Enter does not nothing.

**Comment by fbricon** [comment]
so the default value issue is fixed, you just need to make sure you delete the `quarkus.tools.starter.defaults` preference in you user settings.json

Still, the validation should happen whenever a default value is injected in the field, but I'm afraid that might be a vscode limitation at that point. I'll let @xorye look into it.
