### ISSUE TITLE
Duplicate property detection not useful when using profiles

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-quarkus#87]
Consider
```
quarkus.http.port=8080
%dev.quarkus.http.port=9090
```
- properties appear as duplicate, but they shouldn't since you can define a different value in a profile
- completion is thus not working in the profile (it thinks it's a duplicate)

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/quarkus-ls/pull/98
